const conn = require("../db/db");

//posts Schema
const postsSchema = `CREATE TABLE IF NOT EXISTS posts (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post VARCHAR(255),
    link VARCHAR(255),
    type VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    user_id int
    );`;

conn.query(postsSchema, (err, data) => {
  if (err) console.error(err);
  else console.log("posts table is working");
});

//posts functionality

function getposts(user_id) {
  return conn.query(`SELECT * FROM posts WHERE user_id = $1`, [user_id]);
}
function getAllPosts() {
  return conn.query(`select u.id, u.name, u.username, u.photo, p.post, p.link , p.type , p.created_at
  from users As u JOIN posts AS p ON u.id = p.user_id;`);
}

function createpost(post, link, user_id, type) {
  return conn.query(
    `INSERT into posts(post, link, user_id , type) VALUES($1, $2, $3 , $4)`,
    [post, link, user_id, type]
  );
}

function deletepost(id, user_id) {
  return conn.query(
    `DELETE FROM posts WHERE id = '${id}' AND user_id = '${user_id}'`
  );
}

function updatepost(post, id, user_id) {
  return conn.query(
    `UPDATE posts SET post ='${post}' WHERE id = '${id}' AND user_id = '${user_id}'`
  );
}
module.exports.find = getposts;
module.exports.create = createpost;
module.exports.delete = deletepost;
module.exports.update = updatepost;
module.exports.getAllPosts = getAllPosts;
